routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

//Dashboard
Route::get('/', 'DashboardController@index')->name('home');
Route::get('/home', 'DashboardController@index')->name('home');

// Pages
Route::get('/transactions/asset-disposal', 'PageController@asset_disposal')->name('asset-disposal');
Route::get('/transactions/asset-replacement', 'PageController@asset_replacement')->name('asset-replacement');
Route::get('/transactions/bulk-upload', 'PageController@bulk_upload')->name('bulk-upload');
Route::get('/transactions/loan-assets', 'PageController@loan_asset')->name('loan-assets');
Route::get('/transactions/location-transfer', 'PageController@location_transfer')->name('location-transfer');
Route::get('/transactions/new-asset', 'PageController@new_asset')->name('new-asset');
Route::get('/transactions/open-records', 'PageController@open_records')->name('open-records');
Route::get('/transactions/pre-asset', 'PageController@pre_asset')->name('pre-asset');
Route::get('/transactions/farm-in', 'PageController@farm_in')->name('farm-in');
Route::get('/transactions/farm-out', 'PageController@farm_out')->name('farm-out');
Route::get('/master-files/categories', 'PageController@categories')->name('categories');
Route::get('/master-files/subcategories', 'PageController@subcategories')->name('subcategories');
Route::get('/master-files/brands', 'PageController@brands')->name('brands');
Route::get('/master-files/sites', 'PageController@sites')->name('sites');
Route::get('/master-files/departments', 'PageController@departments')->name('departments');
Route::get('/master-files/employees', 'PageController@employees')->name('employees');
Route::get('/master-files/notifications', 'PageController@notifications')->name('notifications');
Route::get('/master-files/vendors', 'PageController@vendors')->name('vendors');
Route::get('/master-files/business-entities', 'PageController@business_entity')->name('business-entities');
Route::get('/administration/user-management', 'PageController@user_management')->name('user-management');
Route::get('/administration/print-assets', 'PageController@print_assets')->name('print-assets');
Route::get('/administration/request-approvers', 'PageController@request_approvers')->name('request-approvers');
Route::get('/change-password', 'PageController@change_password')->name('change-password');
Route::get('/reports/warranty-report', 'PageController@warranty_report')->name('warranty-report');

//Print Routes
Route::get('/location-transfer/print/{id?}', 'LocationTransferController@print_form')->name('location-transfer.print');

// Export Routes
Route::get('/categories/export/{type?}', 'CategoryController@export')->name('categories.export');
Route::get('/subcategories/export/{type?}', 'SubcategoryController@export')->name('subcategories.export');
Route::get('/brands/export/{type?}', 'BrandController@export')->name('brands.export');
Route::get('/sites/export/{type?}', 'SiteController@export')->name('sites.export');
Route::get('/notifications/export/{type?}', 'NotificationController@export')->name('notifications.export');
Route::get('/vendors/export/{type?}', 'VendorController@export')->name('vendors.export');
Route::get('/departments/export/{type?}', 'DepartmentController@export')->name('departments.export');
Route::get('/employees/export/{type?}', 'EmployeeController@export')->name('employees.export');
Route::get('/business-entities/export/{type?}', 'BusinessEntityController@export')->name('business-entities.export');
Route::get('/user-management/export/{type?}', 'UserController@export')->name('user-management.export');
Route::get('/pre-asset/export/{type?}', 'PreAssetController@export')->name('pre-asset.export'); 
Route::get('/farm-in/export/{type?}', 'FarmInController@export')->name('farm-in.export');
Route::get('/farm-out/export/{type?}', 'FarmOutController@export')->name('farm-out.export');
Route::get('/open-records/export/{type?}', 'AssetController@export')->name('open-records.export');
Route::get('/loan-assets/export/{type?}', 'LoanAssetController@export')->name('loan-assets.export');
Route::get('/asset-disposal/export/{type?}', 'AssetDisposalController@export')->name('asset-disposal.export');
Route::get('/location-transfer/export/{type?}', 'LocationTransferController@export')->name('location-transfer.export');
Route::get('/asset-replacement/export/{type?}', 'AssetReplacementController@export')->name('asset-replacement.export');
Route::get('/new-asset/export/{type?}', 'PreAssetController@pendings_export')->name('new-asset.export');

// Single Route API's
Route::post('/bulk-upload/employees', 'BulkUploadController@employees')->name('bulk.employees');
Route::post('/bulk-upload/assets', 'BulkUploadController@assets')->name('bulk.assets');
Route::get('/attachments/{type}/{id}', 'AttachmentController@show')->name('attachment.show');
Route::get('/asset/{fragment}', 'AssetController@generate')->name('asset.generate');
Route::get('/search-employee', 'EmployeeController@name')->name('employee.name');
Route::get('/search-employees', 'EmployeeController@search')->name('employee.search');
Route::get('/search-pos', 'FarmInController@search')->name('farm-in.search');
Route::get('/po-details/{po}', 'FarmInController@details')->name('farm-in.details');
Route::get('/search-users', 'UserController@search')->name('users.search');
Route::post('/change-password', 'UserController@change')->name('change');
Route::put('/asset-loan/{id}', 'LoanAssetController@action')->name('loan.action');
Route::put('/user-management/reset-password/{id}', 'UserController@reset')->name('user-management.reset');
Route::put('/user-management/set-activation/{id}', 'UserController@activation')->name('user-management.activation');
Route::put('/dispose-asset/{id}', 'AssetDisposalController@action')->name('disposal.action');
Route::put('/replace-asset/{id}', 'AssetReplacementController@action')->name('replace.action');
Route::put('/transfer-asset/{id}', 'LocationTransferController@action')->name('transfer.action');
Route::get('/forgot-password', 'UserController@forgot')->name('forgot-password');
Route::get('/approval/request/{id}', 'ApprovalController@details')->name('request');
Route::get('/request', 'ApprovalController@action')->name('request.action');
Route::get('/history/{id}', 'HistoryController@retrieve')->name('history');
Route::get('/employee/{id}', 'EmployeeController@accountable')->name('accountable');
Route::get('/assets-summary/{scope?}', 'AssetController@summary')->name('asset-summary');
Route::get('/report/warranty/{scope?}', 'ReportController@warranty')->name('report.warranty');
Route::get('/subcategories/name/{id}', 'SubcategoryController@name')->name('subcategories.name');
Route::get('/search-menus', 'UserController@menus')->name('user.menus');
Route::get('/pending-deliveries', 'PreAssetController@pending')->name('pre_asset.pending');
Route::get('/print-assets', 'PrintAssetController@search')->name('print-asset.search');
Route::get('/print-assets/initialize/{printer}', 'PrintAssetController@initialize')->name('print-asset.initialize');
Route::get('/line-items/{po}', 'PreAssetController@items')->name('print-asset.items');

// Resource Routes
Route::resource('approvals', 'ApprovalController', ['only' => ['update']]);
Route::resource('categories', 'CategoryController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('subcategories', 'SubcategoryController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('vendors', 'VendorController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('brands', 'BrandController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('notifications', 'NotificationController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('sites', 'SiteController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('business-entities', 'BusinessEntityController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('employees', 'EmployeeController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('departments', 'DepartmentController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('pre-asset', 'PreAssetController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('loan-assets', 'LoanAssetController', ['only' => ['index', 'store', 'show', 'update', 'destroy']]);
Route::resource('asset-disposal', 'AssetDisposalController', ['only' => ['index', 'store', 'show', 'update', 'destroy']]);
Route::resource('asset-replacement', 'AssetReplacementController', ['only' => ['index', 'store', 'show', 'update', 'destroy']]);
Route::resource('location-transfer', 'LocationTransferController', ['only' => ['index', 'store', 'show', 'update', 'destroy']]);
Route::resource('new-asset', 'AssetController', ['only' => ['store']]);
Route::resource('user-management', 'UserController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('open-records', 'AssetController', ['only' => ['index', 'show', 'update', 'destroy']]);
Route::resource('farm-in', 'FarmInController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('farm-out', 'FarmOutController', ['only' => ['index', 'show', 'update', 'destroy']]);
Route::resource('lookup-values', 'LookupController', ['only' => ['index', 'store', 'show', 'update', 'destroy']]);
Route::resource('request-approvers', 'RequestApproverController', ['only' => ['index', 'store', 'show', 'update', 'destroy']]);

resources/views/administration/master-files/brands.blade.php
@extends('base')
@section('content')
@setvar('view', 'brands')
<div :class="component">
	<form method="POST" ref="{{ $view }}" @submit.prevent @keydown="form.errors.clear($event.target.name)" @change="form.errors.clear($event.target.name)">
	
		<div class="form-group" :class="{'has-error' : form.errors.has('brand_name') }">
			<label>Brand Name</label>
			<input type="type" class="form-control" name="brand_name"  v-model="form.brand_name" required :disabled="form.disabled">
			<span :is="form.errors.message" v-bind:error-message="form.errors.get('brand_name')"></span>
		</div>

	</form>
	
	<div class="table-section">
		<dataset api="{{ route('brands.index') }}" primary="brand_id" :utils="{{ json_encode(['search', 'export']) }}" :paginate="true" :async="true" :info="true" @selected-row="getSelectedRow($event)" export="{{ route('brands.export') }}"></dataset>
	</div>

</div>
@endsection

resources/views/administration/master-files/business-entities.blade.php
@extends('base')
@section('content')
@setvar('view', 'business-entities')
<div :class="component">
	<form method="POST" ref="{{ $view }}" @submit.prevent @keydown="form.errors.clear($event.target.name)" @change="form.errors.clear($event.target.name)">
	
		<div class="form-group" :class="{'has-error' : form.errors.has('lob') }">
			<label>LOB Owner</label>
			<input type="type" class="form-control" name="lob"  v-model="form.lob" required :disabled="form.disabled">
			<span :is="form.errors.message" v-bind:error-message="form.errors.get('lob')"></span>
		</div>

	</form>
	<div class="table-section">
		<dataset api="{{ route('business-entities.index') }}" primary="business_entity_id" :utils="{{ json_encode(['search', 'export']) }}" :paginate="true" :async="true" :info="true" @selected-row="getSelectedRow($event)" :custom-header="{'name': 'LOB Owner'}"  export="{{ route('business-entities.export') }}"></dataset>
	</div>
</div>

@endsection

resources/views/administration/master-files/categories.blade.php
@extends('base')
@section('content')
@setvar('view', 'categories')
<div :class="component">
	<form method="POST" @submit.prevent ref="{{ $view }}" @keydown="form.errors.clear($event.target.name)" @change="form.errors.clear($event.target.name)">

		<div class="form-group" :class="{'has-error' : form.errors.has('category_name')}">
			<label>Category Name</label>
			<input type="text" class="form-control" name="category_name" v-model="form.category_name" :disabled="form.disabled">
			<span :is="form.errors.message" v-bind:error-message="form.errors.get('category_name')"></span>
		</div>

		<div class="form-group" :class="{'has-error' : form.errors.has('category_code')}">
			<label>Category Code</label>
			<input type="text" class="form-control" name="category_code" v-model="form.category_code" :disabled="form.disabled">
			<span :is="form.errors.message" v-bind:error-message="form.errors.get('category_code')"></span>
		</div>
	</form>
	
	<div class="table-section">
		<dataset api="{{ route('categories.index') }}" primary="category_id" :excludes="['type']" :utils="{{ json_encode(['search', 'export']) }}" :paginate="true" :async="true" :info="true" @selected-row="getSelectedRow($event)" :custom-header="headerDefs" export="{{ route('categories.export') }}"></dataset>
	</div>
</div>
@endsection

resources/views/administration/master-files/departments.blade.php
@extends('base')
@section('content')
@setvar('view', 'departments')
<div :class="component">
    <form method="POST" ref="{{ $view }}" @submit.prevent @keydown="form.errors.clear($event.target.name)" @change="form.errors.clear($event.target.name)">
    
        <div class="form-group" :class="{'has-error' : form.errors.has('department_name') }">
            <label>Department Name</label>
            <input type="type" class="form-control" name="department_name"  v-model="form.department_name" required :disabled="form.disabled">
            <span :is="form.errors.message" v-bind:error-message="form.errors.get('department_name')"></span>
        </div>
        
    </form>
    
    <div class="table-section">
        <dataset api="{{ route('departments.index') }}" primary="department_id" :utils="{{ json_encode(['search', 'export']) }}" :paginate="true" :async="true" :info="true" @selected-row="getSelectedRow($event)" export="{{ route('departments.export') }}"></dataset>
    </div>

</div>
@endsection

resources/views/administration/master-files/employees.blade.php
@extends('base', ['search' => 'true'])
@section('content')
@setvar('view', 'employees')
<modal ref="modal" size="90" title="Employees">
	<dataset api="{{ route('employees.index') }}" primary="employee_id" :utils="{{ json_encode(['search', 'export']) }}" :paginate="true" :async="true" :info="true" @selected-row="getSelectedRow($event)" export="{{ route('employees.export') }}"></dataset>
</modal>

<div :class="component">
	<form method="POST" ref="{{ $view }}" @submit.prevent @keydown="form.errors.clear($event.target.name)" @change="form.errors.clear($event.target.name)">
		<div class="row">
			<div>
				<div class="form-group horizontal" :class="{'has-error' : form.errors.has('employee_no') }">
					<label>Employee ID:</label>
					<input type="text" class="form-control" name="employee_no" required v-model="form.employee_no" :disabled="form.disabled">
					<span :is="form.errors.message" v-bind:error-message="form.errors.get('employee_no')"></span>
				</div>

				<div class="form-group horizontal" :class="{'has-error' : form.errors.has('first_name') }">
					<label>First Name:</label>
					<input type="text" class="form-control" name="first_name" required v-model="form.first_name" :disabled="form.disabled">
					<span :is="form.errors.message" v-bind:error-message="form.errors.get('first_name')"></span>
				</div>

				<div class="form-group horizontal" :class="{'has-error' : form.errors.has('middle_name') }">
					<label>Middle Name:</label>
					<input type="text" class="form-control" name="middle_name" v-model="form.middle_name" :disabled="form.disabled">
					<span :is="form.errors.message" v-bind:error-message="form.errors.get('middle_name')"></span>
				</div>

				<div class="form-group horizontal" :class="{'has-error' : form.errors.has('last_name') }">
					<label>Last Name:</label>
					<input type="text" class="form-control" name="last_name" v-model="form.last_name" :disabled="form.disabled">
					<span :is="form.errors.message" v-bind:error-message="form.errors.get('last_name')"></span>
				</div>

				<div class="form-group horizontal" :class="{'has-error' : form.errors.has('work_phone') }">
					<label>Work Phone:</label>
					<input type="text" class="form-control" name="work_phone" v-model="form.work_phone" :disabled="form.disabled">
					<span :is="form.errors.message" v-bind:error-message="form.errors.get('work_phone')"></span>
				</div>

				<div class="form-group horizontal" :class="{'has-error' : form.errors.has('email') }">
					<label>Email:</label>
					<input type="email" class="form-control" name="email" required v-model="form.email" :disabled="form.disabled">
					<span :is="form.errors.message" v-bind:error-message="form.errors.get('email')"></span>
				</div>
			</div>
			<div>
				<div class="form-group horizontal" :class="{'has-error' : form.errors.has('employee_status'), 'disabled': form.disabled }">
					<label>Employee Status:</label>
					<combobox :options="@arr2str($emp_status)" name="employee_status" v-model="form.employee_status"></combobox>
					</multiselect>
					<span :is="form.errors.message" v-bind:error-message="form.errors.get('employee_status')"></span>
				</div>
				<div class="form-group horizontal" :class="{'has-error' : form.errors.has('department'), 'disabled': form.disabled }">
					<label>Department:</label>
					<combobox :options="@arr2str($departments)" name="department" v-model="form.department"></combobox>
					</multiselect>		
					<span :is="form.errors.message" v-bind:error-message="form.errors.get('department')"></span>
				</div>

				<div class="form-group horizontal" :class="{'has-error' : form.errors.has('department_head') }">
					<label>Dept. Head:</label>
					<input type="text" class="form-control" name="department_head" required v-model="form.department_head" :disabled="form.disabled" @open="form.errors.clear('department_head')">
					<span :is="form.errors.message" v-bind:error-message="form.errors.get('department_head')"></span>
				</div>

				<div class="form-group horizontal" :class="{'has-error' : form.errors.has('supervisor') }">
					<label>Supervisor:</label>
					<input type="text" class="form-control" name="supervisor" required v-model="form.supervisor" :disabled="form.disabled" @open="form.errors.clear('supervisor')">
					<span :is="form.errors.message" v-bind:error-message="form.errors.get('supervisor')"></span>
				</div>

				<div class="form-group horizontal" :class="{'has-error' : form.errors.has('date_hired') }">
					<label>Date Hired:</label>
					<div class="input-group">
						<datepicker v-model="form.date_hired" :disabled="form.disabled" :options="{allowInput: true, dateFormat: 'm/d/Y' }" name="date_hired"></datepicker> 
						<span class="input-group-addon">
	                        <i class="fa fa-fw fa-calendar"></i>
	                    </span>
                    </div>
					<span :is="form.errors.message" v-bind:error-message="form.errors.get('date_hired')"></span>
				</div>
			</div>
			<div>
				<div class="img-frame" :class="{active : !form.disabled}">
					<div class="img-wrapper">
						<img id="dp" alt="Employee Image" :src="empImage" />
						<input type="file" name="employee_image" class="hidden" @change="assignImage($event)" accept="image/*">
						<span class="uploader" v-if="!form.disabled" @click="$event.target.previousElementSibling.click()"><i class="fa fa-camera fa-fw"></i> Upload Image</span>
					</div>
				</div>
			</div>
		</div>
		<div class="tab" v-if="identifier">
		<ul>
			<li v-for="(item, key) in togglables" class="items" :class="{active : selected == key}" @click="selected = key">@{{ item }}</li>
		</ul>
		<div class="tab-content" id="accountable_assets" v-if="selected == 0 || selected == ''">
			<div>
				<dataset api="{{ route('open-records.index') }}"  :excludes="['pre_asset']" :default-search="form.first_name + ' ' + form.middle_name + ' ' + form.last_name" :async="true" :paginate="true" link-to="{{ route('open-records') }}" :info="true" ref="accountable_assets"></dataset>
				</div>
			</div>
		<div class="tab-content" id="loaned_assets" v-if="selected == 1">
			<div></div>
		</div>
	</div>
	</form>
	<div class="mass-upload" v-if="upload_mass && !identifier">
		<div class="separator">Mass Create</div>
		<form action="{{ route('bulk.employees') }}" method="POST" enctype="multipart/form-data">
			{{ csrf_field() }}
			<div>
				<a href="/templates/EMPLOYEES_TEMPLATE.xlsx" download><font size="40"><i class="fa fa-file-text-o fa-5X"></i></font>
				<span class="help-block">Click here to download the template.</span></a>
			</div>
			<div>
				<font size="40"><i class="fa fa-info-circle fa-5X"></i></font>
				<span class="help-block">Maximum no. of rows is 1,500. <br>
					Use only template downloaded, to avoid errors.</span>
			</div>
			<div>
				<div>
					<label>Employees File: </label>
					<input type="file" name="employees" @change="massUpload($event)" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet">
					<p class="help-block">Maximum upload file size: 2MB</p>
				</div>
					<component v-bind:is="process_result"></component>
			</div>
		</form>
	</div>
</div>

@endsection

resources/views/administration/master-files/notifications.blade.php
@extends('base')
@section('content')
@setvar('view', 'notifications')
<div :class="component">
	<form method="POST" ref="{{ $view }}" @submit.prevent>
		<div class="form-group" :class="{'has-error' : form.errors.has('group_name') }">
			<label>Group Name</label>
			<input @keyup="form.errors.clear('group_name')" type="type" class="form-control" name="group_name"  v-model="form.group_name" required :disabled="form.disabled">
			<span :is="form.errors.message" v-bind:error-message="form.errors.get('group_name')"></span>
		</div>

        <div class="form-group" :class="{'has-error' : has_error('to_address') }">
			<label>To Address: </label><p class="field-info pull-right help-block"><i class="fa fa-fw fa-info-circle"></i>Insert multiple emails separated by comma ";"</p>
			<textarea rows="5" class="form-control" name="to_address" v-model="to" required :disabled="form.disabled"></textarea>
			<span :is="form.errors.message" v-bind:error-message="get_error('to_address')"></span>
		</div>

		<div class="form-group" :class="{'has-error' : has_error('cc_address') }">
			<label>Cc Address: </label><p class="field-info pull-right help-block"><i class="fa fa-fw fa-info-circle"></i>Insert multiple emails separated by comma ";"</p>
			<textarea rows="5" class="form-control" name="cc_address" v-model="cc" required :disabled="form.disabled"></textarea>
			<span :is="form.errors.message" v-bind:error-message="get_error('cc_address')"></span>
		</div>

	</form>

	<div class="table-section">
		<dataset api="{{ route('notifications.index') }}" primary="notification_id" :utils="{{ json_encode(['search', 'export']) }}" :paginate="true" :async="true" :info="true" @selected-row="getSelectedRow($event)" export="{{ route('notifications.export') }}"></dataset>
	</div>
</div>

@endsection

resources/views/administration/master-files/sites.blade.php
@extends('base')
@section('content')
@setvar('view', 'sites')
<div :class="component">
	<form method="POST" ref="{{ $view }}" @submit.prevent @keydown="form.errors.clear($event.target.name)" @change="form.errors.clear($event.target.name)">
		

		<div class="form-group" :class="{'has-error' : form.errors.has('site_name') }">
			<label>Site Name</label>
			<input type="type" class="form-control" name="site_name"  v-model="form.site_name" required :disabled="form.disabled">
			<span :is="form.errors.message" v-bind:error-message="form.errors.get('site_name')"></span>
		</div>

        <div class="form-group" :class="{'has-error' : form.errors.has('site_code') }">
			<label>Site Code</label>
			<input type="type" class="form-control" name="site_code"  v-model="form.site_code" required :disabled="form.disabled">
			<span :is="form.errors.message" v-bind:error-message="form.errors.get('site_code')"></span>
		</div>

        <div class="form-group" :class="{'has-error' : form.errors.has('address') }">
			<label>Address</label>
			<textarea class="form-control" name="address" rows="10" v-model="form.address" :disabled="form.disabled"></textarea>
			<span :is="form.errors.message" v-bind:error-message="form.errors.get('address')"></span>
		</div>
	</form>
	<div class="table-section">
		<dataset api="{{ route('sites.index') }}" primary="site_id" :utils="{{ json_encode(['search', 'export']) }}" :paginate="true" :async="true" :custom-header="headerDefs" :info="true" @selected-row="getSelectedRow($event)" export="{{ route('sites.export') }}"></dataset>
	</div>

</div>

@endsection

resources/views/administration/master-files/subcategories.blade.php
@extends('base')
@section('content')
@setvar('view', 'subcategories')
<div :class="component">
	<form method="POST" ref="{{ $view }}" @submit.prevent @keydown="form.errors.clear($event.target.name)" @change="form.errors.clear($event.target.name)">

		<div class="form-group" :class="{'has-error' : form.errors.has('category'), 'disabled' : form.disabled} ">
			<label>Category</label>
			<combobox :options="{{ $categories }}" name="category" v-model="form.category" :searchable="true" label="name" track-by="code"></combobox>
			<span :is="form.errors.message" v-bind:error-message="form.errors.get('category')"></span>
		</div>

		<div class="form-group" :class="{'has-error' : form.errors.has('subcategory_name') }">
			<label>Subcategory Name</label>
			<input type="type" class="form-control" name="subcategory_name" v-model="form.subcategory_name" :disabled="form.disabled">
			<div :is="form.errors.message" v-bind:error-message="form.errors.get('subcategory_name')"></div>
		</div>

	</form>
	<div class="table-section">
		<dataset api="{{ route('subcategories.index') }}" primary="category_id" :excludes="['type']" :utils="{{ json_encode(['search', 'export']) }}" :paginate="true" :async="true" :info="true" @selected-row="getSelectedRow($event)" :custom-header="headerDefs" export="{{ route('subcategories.export') }}"></dataset>
	</div>
</div>

@endsection

resources/views/administration/master-files/vendors.blade.php
@extends('base')
@section('content')
@setvar('view', 'vendors')
<div :class="component">
	<form method="POST" ref="{{ $view }}" @submit.prevent @keydown="form.errors.clear($event.target.name)" @change="form.errors.clear($event.target.name)">

		<div class="form-group" :class="{'has-error' : form.errors.has('supplier_name') }">
			<label>Supplier Name</label>
			<input type="type" class="form-control" name="supplier_name"  v-model="form.supplier_name" required :disabled="form.disabled">
			<span :is="form.errors.message" v-bind:error-message="form.errors.get('supplier_name')"></span>
		</div>

        <div class="form-group" :class="{'has-error' : form.errors.has('contact_person') }">
			<label>Contact Person</label>
			<input type="type" class="form-control" name="contact_person"  v-model="form.contact_person" required :disabled="form.disabled">
			<span :is="form.errors.message" v-bind:error-message="form.errors.get('contact_person')"></span>
		</div>

        <div class="form-group" :class="{'has-error' : form.errors.has('contact_number') }">
			<label>Contact Number</label>
			<input type="type" class="form-control" name="contact_number"  v-model="form.contact_number" required :disabled="form.disabled">
			<span :is="form.errors.message" v-bind:error-message="form.errors.get('contact_number')"></span>
		</div>

        <div class="form-group" :class="{'has-error' : form.errors.has('supplier_address') }">
			<label>Supplier Address</label>
			<textarea class="form-control" name="supplier_address" rows="10" v-model="form.supplier_address" :disabled="form.disabled"></textarea>
			<span :is="form.errors.message" v-bind:error-message="form.errors.get('supplier_address')"></span>
		</div>

	</form>
	<div class="table-section">
		<dataset api="{{ route('vendors.index') }}" primary="vendor_id" :utils="{{ json_encode(['search', 'export']) }}" :paginate="true" :async="true" :info="true" @selected-row="getSelectedRow($event)" :custom-header="headerDefs" export="{{ route('vendors.export') }}"></dataset>
	</div>
</div>

@endsection