routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

//Dashboard
Route::get('/', 'DashboardController@index')->name('home');
Route::get('/home', 'DashboardController@index')->name('home');

// Pages
Route::get('/transactions/asset-disposal', 'PageController@asset_disposal')->name('asset-disposal');
Route::get('/transactions/asset-replacement', 'PageController@asset_replacement')->name('asset-replacement');
Route::get('/transactions/bulk-upload', 'PageController@bulk_upload')->name('bulk-upload');
Route::get('/transactions/loan-assets', 'PageController@loan_asset')->name('loan-assets');
Route::get('/transactions/location-transfer', 'PageController@location_transfer')->name('location-transfer');
Route::get('/transactions/new-asset', 'PageController@new_asset')->name('new-asset');
Route::get('/transactions/open-records', 'PageController@open_records')->name('open-records');
Route::get('/transactions/pre-asset', 'PageController@pre_asset')->name('pre-asset');
Route::get('/transactions/farm-in', 'PageController@farm_in')->name('farm-in');
Route::get('/transactions/farm-out', 'PageController@farm_out')->name('farm-out');
Route::get('/master-files/categories', 'PageController@categories')->name('categories');
Route::get('/master-files/subcategories', 'PageController@subcategories')->name('subcategories');
Route::get('/master-files/brands', 'PageController@brands')->name('brands');
Route::get('/master-files/sites', 'PageController@sites')->name('sites');
Route::get('/master-files/departments', 'PageController@departments')->name('departments');
Route::get('/master-files/employees', 'PageController@employees')->name('employees');
Route::get('/master-files/notifications', 'PageController@notifications')->name('notifications');
Route::get('/master-files/vendors', 'PageController@vendors')->name('vendors');
Route::get('/master-files/business-entities', 'PageController@business_entity')->name('business-entities');
Route::get('/administration/user-management', 'PageController@user_management')->name('user-management');
Route::get('/administration/print-assets', 'PageController@print_assets')->name('print-assets');
Route::get('/administration/request-approvers', 'PageController@request_approvers')->name('request-approvers');
Route::get('/change-password', 'PageController@change_password')->name('change-password');
Route::get('/reports/warranty-report', 'PageController@warranty_report')->name('warranty-report');

//Print Routes
Route::get('/location-transfer/print/{id?}', 'LocationTransferController@print_form')->name('location-transfer.print');

// Export Routes
Route::get('/categories/export/{type?}', 'CategoryController@export')->name('categories.export');
Route::get('/subcategories/export/{type?}', 'SubcategoryController@export')->name('subcategories.export');
Route::get('/brands/export/{type?}', 'BrandController@export')->name('brands.export');
Route::get('/sites/export/{type?}', 'SiteController@export')->name('sites.export');
Route::get('/notifications/export/{type?}', 'NotificationController@export')->name('notifications.export');
Route::get('/vendors/export/{type?}', 'VendorController@export')->name('vendors.export');
Route::get('/departments/export/{type?}', 'DepartmentController@export')->name('departments.export');
Route::get('/employees/export/{type?}', 'EmployeeController@export')->name('employees.export');
Route::get('/business-entities/export/{type?}', 'BusinessEntityController@export')->name('business-entities.export');
Route::get('/user-management/export/{type?}', 'UserController@export')->name('user-management.export');
Route::get('/pre-asset/export/{type?}', 'PreAssetController@export')->name('pre-asset.export'); 
Route::get('/farm-in/export/{type?}', 'FarmInController@export')->name('farm-in.export');
Route::get('/farm-out/export/{type?}', 'FarmOutController@export')->name('farm-out.export');
Route::get('/open-records/export/{type?}', 'AssetController@export')->name('open-records.export');
Route::get('/loan-assets/export/{type?}', 'LoanAssetController@export')->name('loan-assets.export');
Route::get('/asset-disposal/export/{type?}', 'AssetDisposalController@export')->name('asset-disposal.export');
Route::get('/location-transfer/export/{type?}', 'LocationTransferController@export')->name('location-transfer.export');
Route::get('/asset-replacement/export/{type?}', 'AssetReplacementController@export')->name('asset-replacement.export');
Route::get('/new-asset/export/{type?}', 'PreAssetController@pendings_export')->name('new-asset.export');

// Single Route API's
Route::post('/bulk-upload/employees', 'BulkUploadController@employees')->name('bulk.employees');
Route::post('/bulk-upload/assets', 'BulkUploadController@assets')->name('bulk.assets');
Route::get('/attachments/{type}/{id}', 'AttachmentController@show')->name('attachment.show');
Route::get('/asset/{fragment}', 'AssetController@generate')->name('asset.generate');
Route::get('/search-employee', 'EmployeeController@name')->name('employee.name');
Route::get('/search-employees', 'EmployeeController@search')->name('employee.search');
Route::get('/search-pos', 'FarmInController@search')->name('farm-in.search');
Route::get('/po-details/{po}', 'FarmInController@details')->name('farm-in.details');
Route::get('/search-users', 'UserController@search')->name('users.search');
Route::post('/change-password', 'UserController@change')->name('change');
Route::put('/asset-loan/{id}', 'LoanAssetController@action')->name('loan.action');
Route::put('/user-management/reset-password/{id}', 'UserController@reset')->name('user-management.reset');
Route::put('/user-management/set-activation/{id}', 'UserController@activation')->name('user-management.activation');
Route::put('/dispose-asset/{id}', 'AssetDisposalController@action')->name('disposal.action');
Route::put('/replace-asset/{id}', 'AssetReplacementController@action')->name('replace.action');
Route::put('/transfer-asset/{id}', 'LocationTransferController@action')->name('transfer.action');
Route::get('/forgot-password', 'UserController@forgot')->name('forgot-password');
Route::get('/approval/request/{id}', 'ApprovalController@details')->name('request');
Route::get('/request', 'ApprovalController@action')->name('request.action');
Route::get('/history/{id}', 'HistoryController@retrieve')->name('history');
Route::get('/employee/{id}', 'EmployeeController@accountable')->name('accountable');
Route::get('/assets-summary/{scope?}', 'AssetController@summary')->name('asset-summary');
Route::get('/report/warranty/{scope?}', 'ReportController@warranty')->name('report.warranty');
Route::get('/subcategories/name/{id}', 'SubcategoryController@name')->name('subcategories.name');
Route::get('/search-menus', 'UserController@menus')->name('user.menus');
Route::get('/pending-deliveries', 'PreAssetController@pending')->name('pre_asset.pending');
Route::get('/print-assets', 'PrintAssetController@search')->name('print-asset.search');
Route::get('/print-assets/initialize/{printer}', 'PrintAssetController@initialize')->name('print-asset.initialize');
Route::get('/line-items/{po}', 'PreAssetController@items')->name('print-asset.items');

// Resource Routes
Route::resource('approvals', 'ApprovalController', ['only' => ['update']]);
Route::resource('categories', 'CategoryController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('subcategories', 'SubcategoryController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('vendors', 'VendorController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('brands', 'BrandController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('notifications', 'NotificationController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('sites', 'SiteController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('business-entities', 'BusinessEntityController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('employees', 'EmployeeController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('departments', 'DepartmentController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('pre-asset', 'PreAssetController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('loan-assets', 'LoanAssetController', ['only' => ['index', 'store', 'show', 'update', 'destroy']]);
Route::resource('asset-disposal', 'AssetDisposalController', ['only' => ['index', 'store', 'show', 'update', 'destroy']]);
Route::resource('asset-replacement', 'AssetReplacementController', ['only' => ['index', 'store', 'show', 'update', 'destroy']]);
Route::resource('location-transfer', 'LocationTransferController', ['only' => ['index', 'store', 'show', 'update', 'destroy']]);
Route::resource('new-asset', 'AssetController', ['only' => ['store']]);
Route::resource('user-management', 'UserController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('open-records', 'AssetController', ['only' => ['index', 'show', 'update', 'destroy']]);
Route::resource('farm-in', 'FarmInController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('farm-out', 'FarmOutController', ['only' => ['index', 'show', 'update', 'destroy']]);
Route::resource('lookup-values', 'LookupController', ['only' => ['index', 'store', 'show', 'update', 'destroy']]);
Route::resource('request-approvers', 'RequestApproverController', ['only' => ['index', 'store', 'show', 'update', 'destroy']]);

resources/views/transactions/asset_disposal.blade.php
@extends('base', ['search' => 'true'])
@section('content')
@setvar('view', 'asset-disposal')

<modal ref="modal" size="90" title="Asset Disposal">
	<dataset api="{{ route('asset-disposal.index') }}" :narrow-search="true" primary="disposal_id" :excludes="['delivery_reference']" :utils="{{ json_encode(['search', 'export']) }}" :paginate="true" :async="true" :info="true" @selected-row="getSelectedRow($event)" export="{{ route('asset-disposal.export') }}"></dataset>
</modal>

<div :class="component">
	<div class="asset-info">
		<h4>Asset Information</h4>
		<div class="img-frame">
			<div class="img-wrapper">
				<img id="dp" alt="Asset Image" :src="image_src" onload="window.URL.revokeObjectURL(this.src);" />
			</div>
		</div>
		<dl class="dl-horizontal" v-for="(val, key) in asset_info">
		  	<dt class="text-capitalize" v-text="key.replace(/_/g, ' ')"></dt>
			<dd v-if="val">@{{ val }}</dd><dd v-else> NONE </dd>
		</dl>
	</div>
	<form method="POST" ref="{{ $view }}" @submit.prevent @keydown="form.errors.clear($event.target.name)" @change="form.errors.clear($event.target.name)" ref="{{ $view }}">
		<div v-if="status == 'PENDING' && isApprover('{{ Auth::user()->username }}')" class="text-center" style="width: 100%; padding: 5px 0px 20px;">
			<div class="btn-group-horizontal" role="group">
				<a class="btn btn-primary btn-md"  @click.prevent="actionRequest('APPROVED')" >
				<i v-if="actionLoader == 'APPROVED'" class="fa fa-spinner fa-spin"></i> <i v-else class="fa fa-fw fa-check"></i> Approve</a>
				<a class="btn btn-danger btn-md"   @click.prevent="actionRequest('DECLINED')" >
				<i v-if="actionLoader == 'DECLINED'" class="fa fa-spinner fa-spin"></i>
				<i v-else class="fa fa-fw fa-times"></i> Decline</a>
			</div>
		</div>
		<div>
			<div class="form-group horizontal" :class="{'has-error' : form.errors.has('asset_id') }">
				<label>Asset ID:</label>
				<input type="text" class="form-control" name="asset_id" v-model="form.asset_id" :disabled="{{ Auth::user()->is_admin() }}">
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('asset_id')"></span>
			</div>
			<div class="form-group horizontal">
					<dl class="dl-horizontal static">
					  	<dt>Approved By:</dt><dd v-if="approved_by">@{{ approved_by }}</dd><dd v-else> NONE </dd>
					</dl>
					<dl class="dl-horizontal static" style="margin-bottom:0">
					  	<dt>Approved Date:</dt><dd v-if="approved_date">@{{ approved_date }}</dd><dd v-else> NONE </dd>
					</dl>
				</div>
			<div class="form-group horizontal" :class="{'has-error' : form.errors.has('disposal_status') }">
				<label>Disposal Status:</label>
				<input type="text" class="form-control" name="disposal_status" v-model="form.disposal_status" :disabled="true">
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('disposal_status')"></span>
			</div>

			<div class="form-group horizontal" :class="{'has-error' : form.errors.has('itaf_no') }">
				<label>ITAF No:</label>
				<input type="text" class="form-control" name="itaf_no" v-model="form.itaf_no" :disabled="form.disabled">
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('itaf_no')"></span>
			</div>

			<div class="form-group horizontal" :class="{'disabled':  form.disabled, 'has-error' : form.errors.has('disposal_method') }">
				<label>Disposal Method:</label>
				<multiselect v-model="form.disposal_method" :options="@arr2str($disposal_methods)" placeholder="" name="disposal_method" :show-labels="false" :searchable="true" @input="form.errors.clear('disposal_method')"></multiselect>
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('disposal_method')"></span>
			</div>

			<div class="form-group horizontal"  :class="{'disabled':  form.disabled, 'has-error' : form.errors.has('approver') }">
				<label>Approver:</label>
				<multiselect :options="{{ $loan_approver }}" :searchable="false" :show-labels="false" name="approver" placeholder="" v-model="approvers" @open="form.errors.clear('approver')" label="group_name" track-by="approver" ref="approvers"></multiselect>
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('approver')"></span>
			</div>

			<div class="form-group horizontal" :class="{'has-error' : form.errors.has('disposal_vendor') }">
				<label>Disposal Vendor:</label>
				<input type="text" class="form-control" name="disposal_vendor" v-model="form.disposal_vendor" :disabled="form.disabled">
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('disposal_vendor')"></span>
			</div>

			<div class="form-group horizontal" :class="{'has-error' : form.errors.has('disposal_remarks') }">
				<label>Remarks:</label>
				<textarea style="height: 80px;" class="form-control" name="disposal_remarks" v-model="form.disposal_remarks" :disabled="form.disabled"></textarea>
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('disposal_remarks')"></span>
			</div>
		</div>
	</form>
</div>
@endsection

resources/views/transactions/asset_replacement.blade.php
@extends('base', ['search' => 'true'])
@section('content')
@setvar('view', 'asset-replacement')

<modal ref="modal" size="90" title="Asset Replacement">
	<dataset api="{{ route('asset-replacement.index') }}" :narrow-search="true" primary="replacement_id" :excludes="['delivery_reference']" :utils="{{ json_encode(['search', 'export']) }}" :paginate="true" :async="true" :info="true" @selected-row="getSelectedRow($event)" export="{{ route('asset-replacement.export') }}"></dataset>
</modal>

<div :class="component">
	<div class="asset-info">
		<h4>Asset Information</h4>
		<div class="img-frame">
			<div class="img-wrapper">
				<img id="dp" alt="Asset Image" :src="image_src" onload="window.URL.revokeObjectURL(this.src);" />
			</div>
		</div>
		<dl class="dl-horizontal" v-for="(val, key) in asset_info">
		  	<dt class="text-capitalize" v-text="key.replace(/_/g, ' ')"></dt>
			<dd v-if="val">@{{ val }}</dd><dd v-else> NONE </dd>
		</dl>
	</div>
	<form method="POST" ref="{{ $view }}" @submit.prevent @keydown="form.errors.clear($event.target.name)" @change="form.errors.clear($event.target.name)" ref="{{ $view }}">
		<div v-if="status == 'PENDING' && isApprover('{{ Auth::user()->username }}')" class="text-center" style="width: 100%; padding: 5px 0px 20px;">
			<div class="btn-group-horizontal" role="group">
				<a class="btn btn-primary btn-md"  @click.prevent="actionRequest('APPROVED')" >
				<i v-if="actionLoader == 'APPROVED'" class="fa fa-spinner fa-spin"></i> <i v-else class="fa fa-fw fa-check"></i> Approve</a>
				<a class="btn btn-danger btn-md"   @click.prevent="actionRequest('DECLINED')" >
				<i v-if="actionLoader == 'DECLINED'" class="fa fa-spinner fa-spin"></i>
				<i v-else class="fa fa-fw fa-times"></i> Decline</a>
			</div>
		</div>
		<div>
			<div class="form-group horizontal" :class="{'has-error' : form.errors.has('asset_id') }">
				<label>Asset ID:</label>
				<input type="text" class="form-control" name="asset_id" v-model="form.asset_id" :disabled="{{ Auth::user()->is_admin() }}">
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('asset_id')"></span>
			</div>
			<div class="form-group horizontal">
					<dl class="dl-horizontal static">
					  	<dt>Approved By:</dt><dd v-if="approved_by">@{{ approved_by }}</dd><dd v-else> NONE </dd>
					</dl>
					<dl class="dl-horizontal static" style="margin-bottom:0">
					  	<dt>Approved Date:</dt><dd v-if="approved_date">@{{ approved_date }}</dd><dd v-else> NONE </dd>
					</dl>
				</div>
			<div class="form-group horizontal" :class="{'has-error' : form.errors.has('replacement_status') }">
				<label>Replacement Status:</label>
				<input type="text" class="form-control" name="replacement_status" v-model="form.replacement_status" :disabled="true">
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('replacement_status')"></span>
			</div>

			<div class="form-group horizontal" :class="{'has-error' : form.errors.has('itaf_no') }">
				<label>ITAF No:</label>
				<input type="text" class="form-control" name="itaf_no" v-model="form.itaf_no" :disabled="form.disabled">
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('itaf_no')"></span>
			</div>

			<div class="form-group horizontal" :class="{'has-error' : form.errors.has('serial_no') }">
				<label>New Serial No:</label>
				<input type="text" class="form-control" name="serial_no" v-model="form.serial_no" :disabled="isSerialNo">
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('serial_no')"></span>
			</div>

			<div class="form-group horizontal"  :class="{'disabled':  form.disabled, 'has-error' : form.errors.has('approver') }">
				<label>Approver:</label>
				<multiselect :options="{{ $loan_approver }}" :searchable="false" :show-labels="false" name="approver" placeholder="" v-model="approvers" @open="form.errors.clear('approver')" label="group_name" track-by="approver" ref="approvers"></multiselect>
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('approver')"></span>
			</div>

			<div class="form-group horizontal" :class="{'has-error' : form.errors.has('replacement_remarks') }">
				<label>Remarks:</label>
				<textarea style="height: 80px;" class="form-control" name="replacement_remarks" v-model="form.replacement_remarks" :disabled="form.disabled"></textarea>
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('replacement_remarks')"></span>
			</div>
		</div>
	</form>
</div>
@endsection

resources/views/transactions/farm_out.blade.php
@extends('base', ['search' => 'true'])
@section('content')
@setvar('view', 'farm-out')

<modal ref="modal" size="90" title="PEZA Farm Out (8105)">
<dataset api="{{ route('farm-out.index') }}" :hide-primary="true" primary="farm_out_id" :excludes="['']" :utils="{{ json_encode(['search', 'export']) }}" :paginate="true" :async="true" :info="true" @selected-row="getSelectedRow($event)" export="{{ route('farm-out.export') }}"></dataset>
</modal>


<div :class="component">	
	<form method="POST" ref="{{ $view }}" @submit.prevent @keydown="form.errors.clear($event.target.name)" @change="form.errors.clear($event.target.name)" ref="{{ $view }}">
	<div class="row">	
		<div>
			<div class="form-group horizontal" :class="{'has-error' : form.errors.has('control_no') }">
				<label>Control No:</label>
				<input type="text" class="form-control" name="control_no" v-model="form.control_no" :disabled="form.disabled">
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('control_no')"></span>
			</div>

			<div class="form-group horizontal" :class="{'has-error' : form.errors.has('location') }">
				<label>Location:</label>
				<input type="text" class="form-control" name="location" v-model="form.location" :disabled="form.disabled">
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('location')"></span>
			</div>

			<div class="form-group horizontal" :class="{ 'has-error' : form.errors.has('vendor') }">
				<label>Vendor:</label>
				<input type="text" class="form-control" name="vendor" v-model="form.vendor" :disabled="form.disabled">
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('vendor')"></span>
			</div>

			<div class="form-group horizontal" :class="{'has-error' : form.errors.has('proforma_invoice_no') }">
				<label>Proforma Invoice No:</label>
				<input type="text" class="form-control" name="proforma_invoice_no" v-model="form.proforma_invoice_no" :disabled="form.disabled">
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('proforma_invoice_no')"></span>
			</div>

			<div class="form-group horizontal" :class="{'has-error' : form.errors.has('proforma_invoice_date') }">
				    <label>Proforma Invoice Date:</label>
				    <div class="input-group">
					    <datepicker v-model="form.proforma_invoice_date" :disabled="form.disabled" :options="{allowInput: true, dateFormat: 'm/d/Y' }" name="proforma_invoice_date"></datepicker> 
					    <span class="input-group-addon">
	                        <i class="fa fa-fw fa-calendar"></i>
	                    </span>
                    </div>
                    <span :is="form.errors.message" v-bind:error-message="form.errors.get('proforma_invoice_date')"></span>
			</div>

			<div class="form-group horizontal" :class="{'has-error' : form.errors.has('final_invoice_no') }">
				<label>Final Invoice No:</label>
				<input type="text" class="form-control" name="final_invoice_no" v-model="form.final_invoice_no" :disabled="form.disabled">
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('final_invoice_no')"></span>
			</div>

			<div class="form-group horizontal" :class="{'has-error' : form.errors.has('final_invoice_date') }">
				    <label>Final Invoice Date:</label>
				    <div class="input-group">
					    <datepicker v-model="form.final_invoice_date" :disabled="form.disabled" :options="{allowInput: true, dateFormat: 'm/d/Y' }" name="final_invoice_date"></datepicker> 
					    <span class="input-group-addon">
	                        <i class="fa fa-fw fa-calendar"></i>
	                    </span>
                    </div>
                    <span :is="form.errors.message" v-bind:error-message="form.errors.get('final_invoice_date')"></span>
			</div>
		</div>
		<div>
			<div class="form-group horizontal" :class="{'disabled' : form.disabled, 'has-error' : form.errors.has('peza_permit_status') }">
				<label>Peza Permit Status:</label>
				<combobox :options="@arr2str(['YES', 'NO', 'Not Applicable'])" name="peza_permit_status" v-model="form.peza_permit_status"></combobox>
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('peza_permit_status')"></span>
			</div>

			<div class="form-group horizontal" :class="{'has-error' : form.errors.has('peza_form_no') }">
				<label>Peza Form No:</label>
				<input type="text" class="form-control" name="peza_form_no" v-model="form.peza_form_no" :disabled="form.disabled">
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('peza_form_no')"></span>
			</div>

			<div class="form-group horizontal" :class="{'has-error' : form.errors.has('peza_approval_no') }">
				<label>Peza Approval No:</label>
				<input type="text" class="form-control" name="peza_approval_no" v-model="form.peza_approval_no" :disabled="form.disabled">
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('peza_approval_no')"></span>
			</div>

			<div class="form-group horizontal" :class="{'has-error' : form.errors.has('request_date') }">
			    <label>Request Date:</label>
			    <div class="input-group">
				    <datepicker v-model="form.request_date" :disabled="form.disabled" :options="{allowInput: true, dateFormat: 'm/d/Y' }" name="request_date"></datepicker> 
				    <span class="input-group-addon">
                        <i class="fa fa-fw fa-calendar"></i>
                    </span>
                </div>
                <span :is="form.errors.message" v-bind:error-message="form.errors.get('request_date')"></span>
			</div>

			<div class="form-group horizontal" :class="{'has-error' : form.errors.has('date_filed') }">
			    <label>Date Filed:</label>
			    <div class="input-group">
				    <datepicker v-model="form.date_filed" :disabled="form.disabled" :options="{allowInput: true, dateFormat: 'm/d/Y' }" name="date_filed"></datepicker> 
				    <span class="input-group-addon">
                        <i class="fa fa-fw fa-calendar"></i>
                    </span>
                </div>
                <span :is="form.errors.message" v-bind:error-message="form.errors.get('date_filed')"></span>
			</div>

			<div class="form-group horizontal" :class="{'has-error' : form.errors.has('remarks') }">
				<label>Remarks:</label>
				<textarea style="height: 65px;" class="form-control" name="remarks" v-model="form.remarks" :disabled="form.disabled"></textarea>
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('remarks')"></span>
			</div>

			<div class="form-group horizontal" :class="{'has-error' : form.errors.has('farm_out_attachments') }">
			    <label>Attachments:</label>
			    <input type="file" name="farm_out_attachments" class="hidden" @change="form.errors.clear('farm_out_attachments');parseFiles('farm_out_attachments')">
			    <div class="input-group">
			    	<input type="text" class="form-control pull-left" style="width: 85%" disabled="disabled" ref="attachment-input">
			    	<button type="button" class="btn btn-primary attachment-btn pull-left" @click.prevent="$event.target.parentElement.previousElementSibling.click()" :disabled="form.disabled">
			    	Browse
			   		</button>
			    </div>
			    <span :is="form.errors.message" v-bind:error-message="form.errors.get('farm_out_attachments')"></span>
			    <small class="help-block" v-if="!form.errors.has('farm_out_attachments')"><em class="pull-right">(Maximum size of 3MB per file)</em></small>
			</div>
			<div class="attachments">
				<ol>
					<li v-for="(file, i) in form.farm_out_attachments">
						<i class="fa fa-fw" :class="mimeType(file.type)" :title="file.type"></i>
						<a :href="file.uri" class="attachment-item" :download="file.name" :title="file.name"> @{{ file.name }} </a>
						<a class="delete-file" v-if="!form.disabled" @click.prevent="form.farm_out_attachments.splice(i, 1)">[delete]</a>
					</li>
				</ol>
			</div>
		</div>
	</div>
	</form>
</div>

@endsection