routes/web.php
<?php
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

//Dashboard
Route::get('/', 'DashboardController@index')->name('home');
Route::get('/home', 'DashboardController@index')->name('home');

// Pages
Route::get('/transactions/asset-disposal', 'PageController@asset_disposal')->name('asset-disposal');
Route::get('/transactions/asset-replacement', 'PageController@asset_replacement')->name('asset-replacement');
Route::get('/transactions/bulk-upload', 'PageController@bulk_upload')->name('bulk-upload');
Route::get('/transactions/loan-assets', 'PageController@loan_asset')->name('loan-assets');
Route::get('/transactions/location-transfer', 'PageController@location_transfer')->name('location-transfer');
Route::get('/transactions/new-asset', 'PageController@new_asset')->name('new-asset');
Route::get('/transactions/open-records', 'PageController@open_records')->name('open-records');
Route::get('/transactions/pre-asset', 'PageController@pre_asset')->name('pre-asset');
Route::get('/transactions/farm-in', 'PageController@farm_in')->name('farm-in');
Route::get('/transactions/farm-out', 'PageController@farm_out')->name('farm-out');
Route::get('/master-files/categories', 'PageController@categories')->name('categories');
Route::get('/master-files/subcategories', 'PageController@subcategories')->name('subcategories');
Route::get('/master-files/brands', 'PageController@brands')->name('brands');
Route::get('/master-files/sites', 'PageController@sites')->name('sites');
Route::get('/master-files/departments', 'PageController@departments')->name('departments');
Route::get('/master-files/employees', 'PageController@employees')->name('employees');
Route::get('/master-files/notifications', 'PageController@notifications')->name('notifications');
Route::get('/master-files/vendors', 'PageController@vendors')->name('vendors');
Route::get('/master-files/business-entities', 'PageController@business_entity')->name('business-entities');
Route::get('/administration/user-management', 'PageController@user_management')->name('user-management');
Route::get('/administration/print-assets', 'PageController@print_assets')->name('print-assets');
Route::get('/administration/request-approvers', 'PageController@request_approvers')->name('request-approvers');
Route::get('/change-password', 'PageController@change_password')->name('change-password');
Route::get('/reports/warranty-report', 'PageController@warranty_report')->name('warranty-report');

//Print Routes
Route::get('/location-transfer/print/{id?}', 'LocationTransferController@print_form')->name('location-transfer.print');

// Export Routes
Route::get('/categories/export/{type?}', 'CategoryController@export')->name('categories.export');
Route::get('/subcategories/export/{type?}', 'SubcategoryController@export')->name('subcategories.export');
Route::get('/brands/export/{type?}', 'BrandController@export')->name('brands.export');
Route::get('/sites/export/{type?}', 'SiteController@export')->name('sites.export');
Route::get('/notifications/export/{type?}', 'NotificationController@export')->name('notifications.export');
Route::get('/vendors/export/{type?}', 'VendorController@export')->name('vendors.export');
Route::get('/departments/export/{type?}', 'DepartmentController@export')->name('departments.export');
Route::get('/employees/export/{type?}', 'EmployeeController@export')->name('employees.export');
Route::get('/business-entities/export/{type?}', 'BusinessEntityController@export')->name('business-entities.export');
Route::get('/user-management/export/{type?}', 'UserController@export')->name('user-management.export');
Route::get('/pre-asset/export/{type?}', 'PreAssetController@export')->name('pre-asset.export'); 
Route::get('/farm-in/export/{type?}', 'FarmInController@export')->name('farm-in.export');
Route::get('/farm-out/export/{type?}', 'FarmOutController@export')->name('farm-out.export');
Route::get('/open-records/export/{type?}', 'AssetController@export')->name('open-records.export');
Route::get('/loan-assets/export/{type?}', 'LoanAssetController@export')->name('loan-assets.export');
Route::get('/asset-disposal/export/{type?}', 'AssetDisposalController@export')->name('asset-disposal.export');
Route::get('/location-transfer/export/{type?}', 'LocationTransferController@export')->name('location-transfer.export');
Route::get('/asset-replacement/export/{type?}', 'AssetReplacementController@export')->name('asset-replacement.export');
Route::get('/new-asset/export/{type?}', 'PreAssetController@pendings_export')->name('new-asset.export');

// Single Route API's
Route::post('/bulk-upload/employees', 'BulkUploadController@employees')->name('bulk.employees');
Route::post('/bulk-upload/assets', 'BulkUploadController@assets')->name('bulk.assets');
Route::get('/attachments/{type}/{id}', 'AttachmentController@show')->name('attachment.show');
Route::get('/asset/{fragment}', 'AssetController@generate')->name('asset.generate');
Route::get('/search-employee', 'EmployeeController@name')->name('employee.name');
Route::get('/search-employees', 'EmployeeController@search')->name('employee.search');
Route::get('/search-pos', 'FarmInController@search')->name('farm-in.search');
Route::get('/po-details/{po}', 'FarmInController@details')->name('farm-in.details');
Route::get('/search-users', 'UserController@search')->name('users.search');
Route::post('/change-password', 'UserController@change')->name('change');
Route::put('/asset-loan/{id}', 'LoanAssetController@action')->name('loan.action');
Route::put('/user-management/reset-password/{id}', 'UserController@reset')->name('user-management.reset');
Route::put('/user-management/set-activation/{id}', 'UserController@activation')->name('user-management.activation');
Route::put('/dispose-asset/{id}', 'AssetDisposalController@action')->name('disposal.action');
Route::put('/replace-asset/{id}', 'AssetReplacementController@action')->name('replace.action');
Route::put('/transfer-asset/{id}', 'LocationTransferController@action')->name('transfer.action');
Route::get('/forgot-password', 'UserController@forgot')->name('forgot-password');
Route::get('/approval/request/{id}', 'ApprovalController@details')->name('request');
Route::get('/request', 'ApprovalController@action')->name('request.action');
Route::get('/history/{id}', 'HistoryController@retrieve')->name('history');
Route::get('/employee/{id}', 'EmployeeController@accountable')->name('accountable');
Route::get('/assets-summary/{scope?}', 'AssetController@summary')->name('asset-summary');
Route::get('/report/warranty/{scope?}', 'ReportController@warranty')->name('report.warranty');
Route::get('/subcategories/name/{id}', 'SubcategoryController@name')->name('subcategories.name');
Route::get('/search-menus', 'UserController@menus')->name('user.menus');
Route::get('/pending-deliveries', 'PreAssetController@pending')->name('pre_asset.pending');
Route::get('/print-assets', 'PrintAssetController@search')->name('print-asset.search');
Route::get('/print-assets/initialize/{printer}', 'PrintAssetController@initialize')->name('print-asset.initialize');
Route::get('/line-items/{po}', 'PreAssetController@items')->name('print-asset.items');

// Resource Routes
Route::resource('approvals', 'ApprovalController', ['only' => ['update']]);
Route::resource('categories', 'CategoryController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('subcategories', 'SubcategoryController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('vendors', 'VendorController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('brands', 'BrandController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('notifications', 'NotificationController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('sites', 'SiteController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('business-entities', 'BusinessEntityController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('employees', 'EmployeeController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('departments', 'DepartmentController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('pre-asset', 'PreAssetController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('loan-assets', 'LoanAssetController', ['only' => ['index', 'store', 'show', 'update', 'destroy']]);
Route::resource('asset-disposal', 'AssetDisposalController', ['only' => ['index', 'store', 'show', 'update', 'destroy']]);
Route::resource('asset-replacement', 'AssetReplacementController', ['only' => ['index', 'store', 'show', 'update', 'destroy']]);
Route::resource('location-transfer', 'LocationTransferController', ['only' => ['index', 'store', 'show', 'update', 'destroy']]);
Route::resource('new-asset', 'AssetController', ['only' => ['store']]);
Route::resource('user-management', 'UserController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('open-records', 'AssetController', ['only' => ['index', 'show', 'update', 'destroy']]);
Route::resource('farm-in', 'FarmInController', ['only' => ['index', 'show', 'store', 'update', 'destroy']]);
Route::resource('farm-out', 'FarmOutController', ['only' => ['index', 'show', 'update', 'destroy']]);
Route::resource('lookup-values', 'LookupController', ['only' => ['index', 'store', 'show', 'update', 'destroy']]);
Route::resource('request-approvers', 'RequestApproverController', ['only' => ['index', 'store', 'show', 'update', 'destroy']]);

resources/views/administration/lookup-values.blade.php
@extends('base')
@section('content')
@setvar('view', 'lookup-values')
<div :class="component">
	<form method="POST" ref="{{ $view }}" @submit.prevent @keydown="form.errors.clear($event.target.name)" @change="form.errors.clear($event.target.name)">
	
		<div class="form-group" :class="{'has-error' : form.errors.has('tag') }">
			<label>Tag</label>
			<multiselect id="tag" :options="@arr2str($tags)" :searchable="true" :show-labels="false" name="tag" placeholder = "" v-model="form.tag"></multiselect>
			<span :is="form.errors.message" v-bind:error-message="form.errors.get('tag')"></span>
		</div>

		<div class="form-group" :class="{'has-error' : form.errors.has('name') }">
			<label>Name</label>
			<input type="type" class="form-control" name="name"  v-model="form.name" required :disabled="form.disabled">
			<span :is="form.errors.message" v-bind:error-message="form.errors.get('name')"></span>
		</div>

	</form>
	
	<div class="table-section">
		<dataset api="{{ route('lookup-values.index') }}" primary="lookup_id" :paginate="true" :async="true" :info="true" @selected-row="getSelectedRow($event)"></dataset>
	</div>

</div>
@endsection

resources/views/administration/print-assets.blade.php
@extends('base')
@section('content')
@setvar('view', 'print-assets')
<div :class="component">
	<form method="POST" ref="{{ $view }}">
		<div class="row" ref="form">
			<div class="heading text-right">
				<h4>Search Assets</h4> 
				<button @click="searchAssets()" type="button" class="btn btn-primary">Search <i class="fa fa-fw fa-search"></i></button>
			</div>
			<div class="content">
				<div>
					<div class="form-group horizontal">
						<label>Asset ID:</label>
						<input type="text" class="form-control" name="asset_id" v-model="form.asset_id">
					</div>
					<div class="form-group horizontal">
						<label>AMR No:</label>
						<input type="text" class="form-control" name="amr_no" v-model="form.amr_no">
					</div>
					<div class="form-group horizontal">
						<label>GR No:</label>
						<input type="text" class="form-control" name="gr_no" v-model="form.gr_no">
					</div>
					<div class="form-group horizontal">
						<label>Serial No:</label>
						<input type="text" class="form-control" name="serial_no" v-model="form.serial_no">
					</div>
					<div class="form-group horizontal">
						<label>Description:</label>
						<input type="text" class="form-control" name="description" v-model="form.description">
					</div>
					<div class="form-group horizontal">
						<label>Brand:</label>
						<combobox :options="@arr2str($brands)" name="brand" :searchable="true" v-model="form.brand"></combobox>
					</div>
					<div class="form-group horizontal">
						<label>Model:</label>
						<input type="text" class="form-control" name="model" v-model="form.model">
					</div>
				</div>
				<div>
					<div class="form-group horizontal">
						<label>Status:</label>
						<combobox :options="@arr2str($status)" name="status" :searchable="false" v-model="form.status"></combobox>
					</div>
					<div class="form-group horizontal">
						<label>Supplier:</label>
						<combobox :options="@arr2str($vendors)" name="vendor" :searchable="true" v-model="form.vendor"></combobox>
					</div>
					<div class="form-group horizontal">
						<label>Category:</label>
						<combobox :options="@arr2str($categories)" name="category" :searchable="true" v-model="form.category"></combobox>
					</div>
					<div class="form-group horizontal">
						<label>Subcategory:</label>
						<input type="text" class="form-control" name="subcategory" v-model="form.subcategory">
					</div>
					<div class="form-group horizontal">
						<label>Lob Owner:</label>
						<combobox :options="@arr2str($lobs)" name="lob_owner" :searchable="true" v-model="form.lob_owner"></combobox>
					</div>
					<div class="form-group horizontal">
						<label>Invoice No:</label>
						<input type="text" class="form-control" name="invoice_no" v-model="form.invoice_no">
					</div>
					<div class="form-group horizontal">
					    <label>Delivery Date:</label>
					    <div class="input-group">
						    <datepicker v-model="form.delivery_receipt_date" :options="{allowInput: true, dateFormat: 'Y-m-d' }" name="delivery_receipt_date"></datepicker> 
						    <span class="input-group-addon">
		                        <i class="fa fa-fw fa-calendar"></i>
		                    </span>
	                    </div>
					</div>
				</div>
				<div>
					<div class="form-group horizontal">
						<label>Bldg:</label>
						<combobox :options="@arr2str($sites)" name="bldg" :searchable="true" v-model="form.bldg"></combobox>
					</div>
					<div class="form-group horizontal">
						<label>Floor:</label>
						<input type="text" class="form-control" name="floor" v-model="form.floor">
					</div>
					<div class="form-group horizontal">
						<label>Cube:</label>
						<input type="text" class="form-control" name="cube" v-model="form.cube">
					</div>
					<div class="form-group horizontal">
						<label>Employee:</label>
						<input type="text" class="form-control" name="employee" v-model="form.employee">
					</div>
					<div class="form-group horizontal">
						<label>PO No:</label>
						<input type="text" class="form-control" name="purchase_order_no" v-model="form.purchase_order_no">
					</div>
					<div class="form-group horizontal">
						<label>DR No:</label>
						<input type="text" class="form-control" name="delivery_receipt_no" v-model="form.delivery_receipt_no">
					</div>
				</div>
			</div>
		</div>
		<div class="print-utils" v-show="toFront">
			<div class="form-group horizontal" style="padding-left: 0">
				<button type="button" class="btn btn-primary" @click="toggleForm()">Display Form
				</button>
			</div>
			<div class="form-group horizontal">
				<label style="margin-right: 10px;">Printer Name:</label>
				<combobox :options="@arr2str($printers)" name="printers" v-model="printer_name"></combobox>
			</div>
		</div>
		<hr style="display: block; width: 100%">
		<dataset ref="records" :marker="true" :hide-primary="false" primary="asset_id" api="{{ route('print-asset.search') }}" :paginate="true" :async="true" :info="true" :excludes="['active', 'vat_paid', 'maintenance_vendor', 'maintenance_start_date', 
		'maintenance_end_date', 'maintenance_remark', 'maintenance_email_notify', 
		'contract_type', 'contract_start_date', 'contract_end_date', 'contract_remarks', 'financial_treatment', 'local_cost_center',
		'cost_center', 'asset_life', 'monthly_depreciation', 'loa_no', 'loa_valid_until_date', 'consumed_asset_life', 'netbook_value', 
		'remaining_asset_life', 'date_fully_depreciated', 'purchase_price_dollar', 'purchase_price_php', 'pre_asset', 'farm_in']"></dataset>
	</form>
</div>
@endsection

resources/views/administration/request-approvers.blade.php
@extends('base')
@section('content')
@setvar('view', 'request-approvers')
<div :class="component">
	<form method="POST" ref="{{ $view }}" @submit.prevent @keydown="form.errors.clear($event.target.name)" @change="form.errors.clear($event.target.name)">
	
		<div class="form-group" :class="{'has-error' : form.errors.has('group_name') }">
			<label>Group</label>
			<input type="type" class="form-control" name="group_name"  v-model="form.group_name" required :disabled="form.disabled">
			<span :is="form.errors.message" v-bind:error-message="form.errors.get('group_name')"></span>
		</div>

		<div class="form-group" :class="{'has-error' : form.errors.has('approver'), 'disabled' : form.disabled }">
			<label>Approver:</label>
			<multiselect :options="users" v-model="user" :searchable="true" :loading="isLoading" :internal-search="true" @search-change="asyncFindUsers" ref="approvers" :custom-label="customLabel" :show-labels="false" track-by="full_name" label="full_name" placeholder="">
				<template slot="option" scope="props">
				<div class="option__desc"><span class="option__title">@{{ props.option.full_name }}</span><span class="option__small"><p class="pull-right">@{{ props.option.username }}</p></span></div>
	    		</template>
				<span slot="noResult">No records found.</span>
	    	</multiselect>
			<span :is="form.errors.message" v-bind:error-message="form.errors.get('approver')"></span>
		</div>

	</form>
	
	<div class="table-section">
		<dataset utils="{{ json_encode(['search', 'export']) }}" api="{{ route('request-approvers.index') }}" primary="approver_id" :paginate="true" :async="true" :info="true" @selected-row="getSelectedRow($event)"></dataset>
	</div>

</div>
@endsection

resources/views/administration/user-management.blade.php
@extends('base', ['search' => 'true'])
@section('content')
@setvar('view', 'user-management')

<modal ref="modal" size="90" title="Users">
	<dataset api="{{ route('user-management.index') }}" primary="id" :utils="{{ json_encode(['search', 'export']) }}" :paginate="true" :async="true" :info="true" @selected-row="getSelectedRow($event)" export="{{ route('user-management.export') }}"></dataset>
</modal>

<div :class="component">
	<form method="POST" ref="{{ $view }}" @submit.prevent @keydown="form.errors.clear($event.target.name)" @change="form.errors.clear($event.target.name)">
		<div>

			@if(Auth::user()->getOriginal('role') == App\Models\User::ROLE_ADMINISTRATOR)
				<div v-if="identifier" class="form-group text-right">
					<button v-if="enabled" type="button" class="btn btn-danger" value="0" @click="setActivation($event)">
						<i></i> Deactivate Account
					</button>
					<button v-else type="button" class="btn btn-success" value="1" @click="setActivation($event)">
						<i></i> Activate Account
					</button>
					<button type="button" class="btn btn-warning" @click="resetPassword($event)">
						<i></i> Reset Password
					</button>
				</div>
			@endif

			<div class="form-group" :class="{'has-error' : form.errors.has('username') }">
				<label>Username:</label>
				<input type="text" class="form-control" name="username" v-model="form.username" :disabled="form.disabled || identifier">
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('username')"></span>
			</div>

			<div class="form-group horizontal"  :class="{'has-error' : form.errors.has('role'), 'disabled' : form.disabled }">
				<label>Role:</label>
				<multiselect :options="{{ $roles }}" :disabled="form.disabled" name="role" v-model="form.role"></multiselect>
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('role')"></span>
			</div>

			<div class="form-group horizontal"  :class="{'has-error' : form.errors.has('group'), 'disabled' : form.disabled }">
					<label>Group:</label>
					<div style="display: inline-block; margin-left: 10px" ref="groups">
						@foreach($groups as $key => $group)
							@if($key > 0) 
							<label class="group-checkbox">
							<input type="checkbox" :checked="this.form.group == '0' || this.form.group == '{{ $key }}'" @click="setGroup($event)" :disabled="form.disabled" value="{{ $key }}">{{ strtoupper($group) }}</label>
							@endif
						@endforeach
					</div>
			</div>

			<div class="form-group" :class="{'has-error' : form.errors.has('email') }">
				<label>Email:</label>
				<input type="email" class="form-control" name="email" v-model="form.email" :disabled="form.disabled">
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('email')"></span>
			</div>

			<div class="form-group" :class="{'has-error' : form.errors.has('first_name') }">
				<label>First Name:</label>
				<input type="first_name" class="form-control" name="first_name" v-model="form.first_name" :disabled="form.disabled">
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('first_name')"></span>
			</div>

			<div class="form-group" :class="{'has-error' : form.errors.has('middle_name') }">
				<label>Middle Name:</label>
				<input type="middle_name" class="form-control" name="middle_name" v-model="form.middle_name" :disabled="form.disabled">
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('middle_name')"></span>
			</div>

			<div class="form-group" :class="{'has-error' : form.errors.has('last_name') }">
				<label>Last Name:</label>
				<input type="last_name" class="form-control" name="last_name" v-model="form.last_name" :disabled="form.disabled">
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('last_name')"></span>
			</div>

			<div class="form-group"  :class="{'disabled': form.disabled, 'has-error' : form.errors.has('scope') }">
				<label>Scope:</label>
				<multiselect v-model="form.scope" :disabled="form.disabled" :multiple="true" :options="{{ $sites }}" name="scope" :searchable="true"></multiselect>
				<span :is="form.errors.message" v-bind:error-message="form.errors.get('scope')"></span>
			</div>
		</div>		
		<div>
			<div class="panel-head">Access Control</div>
			<div class="panel-content">
				<div class="list-utils">
					<div class="form-group" :class="{'has-error' : form.errors.has('modules'), 'disabled' : form.disabled }">
						<multiselect ref="menus" :disabled="form.disabled" :options="parseOption({{ $menus }})" v-model="form.modules" name="modules" :searchable="true" :multiple="true" :input-value="current" :hide-tags="true" @remove="getRemoved($event)" :close-on-select="true" @select="getSelected($event)"></multiselect>
					</div>
					<div class="form-group">
						<div v-if="transactions" class="checkbox">
							<label v-for="(i, item) in transactions">
							<input type="checkbox" v-model="transactions[item]" value="1">@{{ item }}</label>
							<button class="btn btn-default" :disabled=" this.form.errors.has('user_permission')" @click="addUserPrivilege()"><i class="fa fa-fw fa-plus"></i></button>
						</div>
					</div>
				</div>
			</div>
			<table class="table table-hover" v-if="form.modules.length" :class="{ 'disabled' : form.disabled }">
				<thead>
					<th>Modules</th>
					<th>Permission</th>
				</thead>
				<tbody>
					<tr v-for="(item, index) in accessPrivilege" v-on:click="!form.disabled && displaySelected(index)">
						<td>@{{ item.name }}</td>
						<td>@{{ item.permission }}</td>
					</tr>
				</tbody>
			</table>
		</div>
	</form>
</div>
@endsection